language: go
go:
    - 1.10
script:
    - go test -v
    - go build
    - gox -osarch="linux/386 linux/amd64 darwin/amd64" -output="out/{{.Dir}}-{{.OS}}-{{.Arch}}" github.com/csigildea/CS3021_Software_Engineering-LCA
env:
    global:
notifications:
    on_success: never
    on_failure: never

